### ISSUE TITLE
GaussDB NoSQL - API Reference - Missing Endpoint

### ISSUE THREAD

**Issue by nr-21** [opentelekomcloud-docs/gaussdb-nosql#26]
The Endpoint for GaussDB for Cassandra is missing from the following page. https://docs.otc.t-systems.com/additional/endpoints.html

Issue on page:        https://github.com/opentelekomcloud-docs/gaussdb-nosql/blob/main/api-ref/source/index.rst

**Comment by lboka** [comment]
Hello,
Internal ticket was opened for this issue OTCDB-4932. We will inform you once issue is solved.

**Comment by lboka** [comment]
Endpoint is now present on the page. 
<img width="835" alt="image" src="https://github.com/opentelekomcloud-docs/gaussdb-nosql/assets/96316177/ee2ada62-1e52-43b8-bd75-734b3c908012">
